### ISSUE TITLE
streamlit version 1.21.0 compatability

### ISSUE THREAD

**Issue by tonyhollaar** [Mr-Milk/streamlit-state#2]
Great package - just what i needed to have forms with Streamlit sliders to save their session states when switching pages for multi-page Streamlit app!

However please change in **state.py** file the following line for compatability with streamlit v1.21.0, otherwise locally I did not get it to work when importing the package after a pip install:
```
#from streamlit.scriptrunner import get_script_run_ctx
from streamlit.runtime.scriptrunner.script_run_context import get_script_run_ctx

```

**Comment by Mr-Milk** [comment]
Sure, I will make a new release soon.

**Comment by Mr-Milk** [comment]
Just release the new version

**Comment by tonyhollaar** [comment]
Much appreciated! Thank you for the update.
